In [1]:
import numpy as np
from sklearn.utils import compute_class_weight

In [11]:
n_classes = 4
zero = np.array([1,0,0,0]*717).reshape((717,4))
one = np.array([0,1,0,0]*52).reshape((52,4))
two = np.array([0,0,1,0]*2560).reshape((2560,4))
three = np.array([0,0,0,1]*1792).reshape((1792,4))

full_labels= np.concatenate((zero,one,two,three),axis=0)
y_integers = np.argmax(full_labels, axis=1)

In [12]:
print(full_labels)
print(y_integers)

[[1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 ...
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]]
[0 0 0 ... 3 3 3]


In [14]:
class_weights = compute_class_weight('balanced', classes=np.unique(y_integers), y=y_integers)
d_class_weights = dict(enumerate(class_weights))
print(d_class_weights)

{0: 1.7855648535564854, 1: 24.620192307692307, 2: 0.50009765625, 3: 0.7144252232142857}
